### ISSUE TITLE
CASA also not working in Jovial

### ISSUE THREAD

**Issue by maray** [ChileanVirtualObservatory/jovial.chivo.cl#13]
Because of LustreFS, we now cannot run CASA at Jovial. This is probably due to the same locking configuration when mounting than issue #12. Even though we might have performance degradation in Lustre we need to change the mounting.

```
CASA Version 4.7.16-DEV (r36528)
  Compiled on: Tue 2016/03/29 04:18:30 UTC
2017-09-12 11:44:02     SEVERE          Exception Reported: Error (Function not implemented) when acquiring lock on /home/maray/cas
a/casa-monthly-4.7.16/data/geodetic/Observatories/table.lock
Traceback (most recent call last):
  File "/home/maray/casa/casa-monthly-4.7.16/lib/python2.7/casapy.py", line 457, in <module>
    from taskinit import *
  File "/home/maray/casa/casa-monthly-4.7.16/lib/python2.7/taskinit.py", line 145, in <module>
    im,cb,ms,tb,me,ia,po,sm,cl,cs,rg,sl,dc,vp,msmd,fi,fn,imd,sdms,lm=gentools()
  File "/home/maray/casa/casa-monthly-4.7.16/lib/python2.7/taskinit.py", line 143, in gentools
    return tuple([eval(tooldic[reqtool]) for reqtool in reqtools])
  File "<string>", line 1, in <module>
  File "/home/maray/casa/casa-monthly-4.7.16/lib/python2.7/__casac__/vpmanager.py", line 79, in __init__
    this = _vpmanager.new_vpmanager()
RuntimeError: Error (Function not implemented) when acquiring lock on /home/maray/casa/casa-monthly-4.7.16/data/geodetic/Observator
ies/table.lock
```

**Comment by madiazp** [comment]
Need the command to reproduce the error
